### ISSUE TITLE
tokenize.TokenError: ('EOF in multi-line statement', (7, 0))

### ISSUE THREAD

**Issue by srid** [cburroughs/pep8.py#5] opened 2009-10-04 07:35 UTC
```
$ pep8 src/pypm/client/
src/pypm/client/.DS_Store:2:80: E501 line too long (1169 characters)
src/pypm/client/.DS_Store:6:2029: W292 no newline at end of file
Traceback (most recent call last):
  File "/Users/sridharr/.local/bin/pep8", line 8, in <module>
    load_entry_point('pep8==0.3.1', 'console_scripts', 'pep8')()
  File "/Users/sridharr/.local/lib/python2.6/site-packages/pep8.py", line 854, in _main
    input_dir(path)
  File "/Users/sridharr/.local/lib/python2.6/site-packages/pep8.py", line 707, in input_dir
    input_file(os.path.join(root, filename))
  File "/Users/sridharr/.local/lib/python2.6/site-packages/pep8.py", line 684, in input_file
    errors = Checker(filename).check_all()
  File "/Users/sridharr/.local/lib/python2.6/site-packages/pep8.py", line 620, in check_all
    for token in tokenize.generate_tokens(self.readline_check_physical):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/tokenize.py", line 352, in generate_tokens
    raise TokenError, ("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (7, 0))
```

**Comment by SmileyChris** [comment] 2009-10-04 10:09
Really a duplicate of issue 2

**Comment by cburroughs** [comment] 2009-10-04 18:55
Thanks to User/SmileyChris for doing all of my triaging for me.  Closing as dupe of issue #2.

**Closed as completed** 2009-10-04 18:55 UTC
